[project]
name = "alto"
namespace = "Alto"
version = "0.1.0"

[source]
dirs = ["wrap/tcell", "wrap/terminal", "src", "examples"]
entry = "Main.start"

[[target]]
name = "hello"
entry = "HelloApp.start"
output = "hello"

[[target]]
name = "counter"
entry = "CounterApp.start"
output = "counter"

[[target]]
name = "dashboard"
entry = "DashboardApp.start"
output = "dashboard"

[[target]]
name = "todo"
entry = "TodoApp.start"
output = "todo"

[go-wrap]
output = "wrap"

[[go-wrap.packages]]
import = "github.com/gdamore/tcell/v2"
include = [
  "NewEventKey", "NewEventMouse", "NewEventResize",
  "NewRGBColor", "NewHexColor", "PaletteColor", "GetColor",
  "ColorBlack", "ColorWhite", "ColorRed", "ColorGreen", "ColorBlue",
  "ColorYellow", "ColorMagenta", "ColorCyan",
  "Style", "EventKey", "EventMouse", "EventResize",
  "CellBuffer",
]

[[go-wrap.packages]]
import = "alto/go/terminal"
