// Code generated by mag wrap alto/go/terminal. DO NOT EDIT.
package wrap_terminal

import (
	"reflect"

	pkg "alto/go/terminal"
	"github.com/chazu/maggie/vm"
)

var _ = reflect.TypeOf

// RegisterPrimitives registers all wrapped Go types and functions with the VM.
func RegisterPrimitives(v *vm.VM) {
	// Type: Screen
	screenClass := v.RegisterGoType("Go::Terminal::Screen", reflect.TypeOf((*pkg.Screen)(nil)))

	// Package namespace class for class-level methods
	nsClass := v.RegisterGoType("Go::Terminal", reflect.TypeOf((*struct{})(nil)))
	_ = nsClass

	nsClass.AddClassMethod(v.Selectors, "newScreen", vm.NewPrimitiveMethod("newScreen", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result := pkg.NewScreen()
		return v.GoToValue(result)
	}))

	screenClass.AddPrimitiveMethod(v.Selectors, "clear", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Clear()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "disableMouse", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.DisableMouse()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "disablePaste", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.DisablePaste()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "enableMouse", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.EnableMouse()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "enablePaste", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.EnablePaste()
		return vm.Nil
	})

	// Skipped: Screen.Fill (unconvertible parameter type: github.com/gdamore/tcell/v2.Style)
	screenClass.AddPrimitiveMethod(v.Selectors, "fini", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Fini()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "getContent:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		r0, r1 := self.GetContent(arg0, arg1)
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "hasMouse", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		result := self.HasMouse()
		return v.GoToValue(result)
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "hideCursor", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.HideCursor()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "init", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Init()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "pollEvent", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		result := self.PollEvent()
		return v.GoToValue(result)
	})

	// Skipped: Screen.PostEvent (unconvertible parameter type: github.com/gdamore/tcell/v2.Event)
	// Skipped: Screen.SetContent (unconvertible parameter type: github.com/gdamore/tcell/v2.Style)
	// Skipped: Screen.SetCursorStyle (unconvertible parameter type: github.com/gdamore/tcell/v2.CursorStyle)
	// Skipped: Screen.SetStyle (unconvertible parameter type: github.com/gdamore/tcell/v2.Style)
	screenClass.AddPrimitiveMethod(v.Selectors, "show", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Show()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "showCursor:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		self.ShowCursor(arg0, arg1)
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "size", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		r0, r1 := self.Size()
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "sync", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Sync()
		return vm.Nil
	})

}
