// Code generated by mag wrap alto/go/terminal. DO NOT EDIT.
package wrap_terminal

import (
	"reflect"

	pkg "alto/go/terminal"
	"github.com/chazu/maggie/vm"
)

var _ = reflect.TypeOf

// RegisterPrimitives registers all wrapped Go types and functions with the VM.
func RegisterPrimitives(v *vm.VM) {
	// Type: Screen
	screenClass := v.RegisterGoType("Go::Terminal::Screen", reflect.TypeOf((*pkg.Screen)(nil)))
	// Type: Style
	styleClass := v.RegisterGoType("Go::Terminal::Style", reflect.TypeOf((*pkg.Style)(nil)))

	// Package namespace class for class-level methods
	nsClass := v.RegisterGoType("Go::Terminal", reflect.TypeOf((*struct{})(nil)))
	_ = nsClass

	nsClass.AddClassMethod(v.Selectors, "debugLog:", vm.NewPrimitiveMethod("debugLog:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0]).(string)
		pkg.DebugLog(arg0)
		return vm.Nil
	}))

	nsClass.AddClassMethod(v.Selectors, "defaultStyle", vm.NewPrimitiveMethod("defaultStyle", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result := pkg.DefaultStyle()
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newScreen", vm.NewPrimitiveMethod("newScreen", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result := pkg.NewScreen()
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newStyle", vm.NewPrimitiveMethod("newStyle", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result := pkg.NewStyle()
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newWrappedStyle", vm.NewPrimitiveMethod("newWrappedStyle", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result := pkg.NewWrappedStyle()
		return v.GoToValue(result)
	}))

	screenClass.AddPrimitiveMethod(v.Selectors, "clear", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Clear()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "disableMouse", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.DisableMouse()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "disablePaste", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.DisablePaste()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "enableMouse", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.EnableMouse()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "enablePaste", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.EnablePaste()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "fill:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		arg0 := rune(args[0].SmallInt())
		arg1 := v.ValueToGo(args[1]).(*pkg.Style)
		self.Fill(arg0, arg1)
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "fini", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Fini()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "getContent:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		r0, r1 := self.GetContent(arg0, arg1)
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "hasMouse", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		result := self.HasMouse()
		return v.GoToValue(result)
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "hideCursor", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.HideCursor()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "init", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Init()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "pollEvent", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		result := self.PollEvent()
		return v.GoToValue(result)
	})

	// Skipped: Screen.PostEvent (unconvertible parameter type: github.com/gdamore/tcell/v2.Event)
	screenClass.AddPrimitiveMethod(v.Selectors, "setContent:_:_:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		arg2 := rune(args[2].SmallInt())
		arg3 := v.ValueToGo(args[3]).(*pkg.Style)
		self.SetContent(arg0, arg1, arg2, arg3)
		return vm.Nil
	})

	// Skipped: Screen.SetCursorStyle (unconvertible parameter type: github.com/gdamore/tcell/v2.CursorStyle)
	screenClass.AddPrimitiveMethod(v.Selectors, "setStyle:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		arg0 := v.ValueToGo(args[0]).(*pkg.Style)
		self.SetStyle(arg0)
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "show", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Show()
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "showCursor:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		self.ShowCursor(arg0, arg1)
		return vm.Nil
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "size", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		r0, r1 := self.Size()
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

	screenClass.AddPrimitiveMethod(v.Selectors, "sync", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Screen)
		self.Sync()
		return vm.Nil
	})

	// Skipped: Style.Background (unconvertible parameter type: github.com/gdamore/tcell/v2.Color)
	styleClass.AddPrimitiveMethod(v.Selectors, "bold:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.Bold(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "dim:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.Dim(arg0)
		return v.GoToValue(result)
	})

	// Skipped: Style.Foreground (unconvertible parameter type: github.com/gdamore/tcell/v2.Color)
	styleClass.AddPrimitiveMethod(v.Selectors, "italic:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.Italic(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "reverse:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.Reverse(arg0)
		return v.GoToValue(result)
	})

}
