// Code generated by mag wrap github.com/gdamore/tcell/v2. DO NOT EDIT.
package wrap_tcell

import (
	"reflect"
	"fmt"

	pkg "github.com/gdamore/tcell/v2"
	"github.com/chazu/maggie/vm"
)

var _ = reflect.TypeOf
var _ = fmt.Errorf

// RegisterPrimitives registers all wrapped Go types and functions with the VM.
func RegisterPrimitives(v *vm.VM) {
	// Type: CellBuffer
	cellBufferClass := v.RegisterGoType("Go::V2::CellBuffer", reflect.TypeOf((*pkg.CellBuffer)(nil)))
	// Type: EventClipboard
	eventClipboardClass := v.RegisterGoType("Go::V2::EventClipboard", reflect.TypeOf((*pkg.EventClipboard)(nil)))
	// Type: EventError
	eventErrorClass := v.RegisterGoType("Go::V2::EventError", reflect.TypeOf((*pkg.EventError)(nil)))
	// Type: EventFocus
	v.RegisterGoType("Go::V2::EventFocus", reflect.TypeOf((*pkg.EventFocus)(nil)))
	// Type: EventInterrupt
	eventInterruptClass := v.RegisterGoType("Go::V2::EventInterrupt", reflect.TypeOf((*pkg.EventInterrupt)(nil)))
	// Type: EventKey
	eventKeyClass := v.RegisterGoType("Go::V2::EventKey", reflect.TypeOf((*pkg.EventKey)(nil)))
	// Type: EventMouse
	eventMouseClass := v.RegisterGoType("Go::V2::EventMouse", reflect.TypeOf((*pkg.EventMouse)(nil)))
	// Type: EventPaste
	eventPasteClass := v.RegisterGoType("Go::V2::EventPaste", reflect.TypeOf((*pkg.EventPaste)(nil)))
	// Type: EventResize
	eventResizeClass := v.RegisterGoType("Go::V2::EventResize", reflect.TypeOf((*pkg.EventResize)(nil)))
	// Type: EventTime
	eventTimeClass := v.RegisterGoType("Go::V2::EventTime", reflect.TypeOf((*pkg.EventTime)(nil)))
	// Type: SimCell
	v.RegisterGoType("Go::V2::SimCell", reflect.TypeOf((*pkg.SimCell)(nil)))
	// Type: Style
	styleClass := v.RegisterGoType("Go::V2::Style", reflect.TypeOf((*pkg.Style)(nil)))
	// Type: WindowSize
	windowSizeClass := v.RegisterGoType("Go::V2::WindowSize", reflect.TypeOf((*pkg.WindowSize)(nil)))

	// Package namespace class for class-level methods
	nsClass := v.RegisterGoType("Go::V2", reflect.TypeOf((*struct{})(nil)))
	_ = nsClass

	// Skipped: FindColor (unconvertible parameter type: []github.com/gdamore/tcell/v2.Color)
	// Skipped: FromImageColor (unconvertible parameter type: image/color.Color)
	nsClass.AddClassMethod(v.Selectors, "getColor:", vm.NewPrimitiveMethod("getColor:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0]).(string)
		result := pkg.GetColor(arg0)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "getEncoding:", vm.NewPrimitiveMethod("getEncoding:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0]).(string)
		result := pkg.GetEncoding(arg0)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "lookupTerminfo:", vm.NewPrimitiveMethod("lookupTerminfo:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0]).(string)
		result, err := pkg.LookupTerminfo(arg0)
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newConsoleScreen", vm.NewPrimitiveMethod("newConsoleScreen", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result, err := pkg.NewConsoleScreen()
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newDevTty", vm.NewPrimitiveMethod("newDevTty", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result, err := pkg.NewDevTty()
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newDevTtyFromDev:", vm.NewPrimitiveMethod("newDevTtyFromDev:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0]).(string)
		result, err := pkg.NewDevTtyFromDev(arg0)
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newEventClipboard:", vm.NewPrimitiveMethod("newEventClipboard:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := []byte(v.ValueToGo(args[0]).(string))
		result := pkg.NewEventClipboard(arg0)
		return v.GoToValue(result)
	}))

	// Skipped: NewEventError (unconvertible parameter type: error)
	nsClass.AddClassMethod(v.Selectors, "newEventFocus:", vm.NewPrimitiveMethod("newEventFocus:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := pkg.NewEventFocus(arg0)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newEventInterrupt:", vm.NewPrimitiveMethod("newEventInterrupt:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0])
		result := pkg.NewEventInterrupt(arg0)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newEventKey:_:_:", vm.NewPrimitiveMethod("newEventKey:_:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := pkg.Key(args[0].SmallInt())
		arg1 := rune(args[1].SmallInt())
		arg2 := pkg.ModMask(args[2].SmallInt())
		result := pkg.NewEventKey(arg0, arg1, arg2)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newEventMouse:_:_:_:", vm.NewPrimitiveMethod("newEventMouse:_:_:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		arg2 := pkg.ButtonMask(args[2].SmallInt())
		arg3 := pkg.ModMask(args[3].SmallInt())
		result := pkg.NewEventMouse(arg0, arg1, arg2, arg3)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newEventPaste:", vm.NewPrimitiveMethod("newEventPaste:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := pkg.NewEventPaste(arg0)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newEventResize:_:", vm.NewPrimitiveMethod("newEventResize:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		result := pkg.NewEventResize(arg0, arg1)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newHexColor:", vm.NewPrimitiveMethod("newHexColor:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := int32(args[0].SmallInt())
		result := pkg.NewHexColor(arg0)
		return v.GoToValue(result)
	}))

	// Skipped: NewInputProcessor (unconvertible parameter type: chan<- github.com/gdamore/tcell/v2.Event)
	nsClass.AddClassMethod(v.Selectors, "newRGBColor:_:_:", vm.NewPrimitiveMethod("newRGBColor:_:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := int32(args[0].SmallInt())
		arg1 := int32(args[1].SmallInt())
		arg2 := int32(args[2].SmallInt())
		result := pkg.NewRGBColor(arg0, arg1, arg2)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newScreen", vm.NewPrimitiveMethod("newScreen", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result, err := pkg.NewScreen()
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newSimulationScreen:", vm.NewPrimitiveMethod("newSimulationScreen:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0]).(string)
		result := pkg.NewSimulationScreen(arg0)
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newStdIoTty", vm.NewPrimitiveMethod("newStdIoTty", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result, err := pkg.NewStdIoTty()
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "newTerminfoScreen", vm.NewPrimitiveMethod("newTerminfoScreen", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		result, err := pkg.NewTerminfoScreen()
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	}))

	// Skipped: NewTerminfoScreenFromTty (unconvertible parameter type: github.com/gdamore/tcell/v2.Tty)
	// Skipped: NewTerminfoScreenFromTtyTerminfo (unconvertible parameter type: github.com/gdamore/tcell/v2.Tty)
	nsClass.AddClassMethod(v.Selectors, "paletteColor:", vm.NewPrimitiveMethod("paletteColor:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := int(args[0].SmallInt())
		result := pkg.PaletteColor(arg0)
		return v.GoToValue(result)
	}))

	// Skipped: RegisterEncoding (unconvertible parameter type: golang.org/x/text/encoding.Encoding)
	nsClass.AddClassMethod(v.Selectors, "setEncodingFallback:", vm.NewPrimitiveMethod("setEncodingFallback:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := pkg.EncodingFallback(args[0].SmallInt())
		pkg.SetEncodingFallback(arg0)
		return vm.Nil
	}))

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "dirty:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		result := self.Dirty(arg0, arg1)
		return v.GoToValue(result)
	})

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "fill:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		arg0 := rune(args[0].SmallInt())
		arg1 := *v.ValueToGo(args[1]).(*pkg.Style)
		self.Fill(arg0, arg1)
		return vm.Nil
	})

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "get:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		r0, r1, r2 := self.Get(arg0, arg1)
		arr := make([]vm.Value, 3)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		arr[2] = v.GoToValue(r2)
		return v.NewArrayWithElements(arr)
	})

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "getContent:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		r0, r1, r2, r3 := self.GetContent(arg0, arg1)
		arr := make([]vm.Value, 4)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		arr[2] = v.GoToValue(r2)
		arr[3] = v.GoToValue(r3)
		return v.NewArrayWithElements(arr)
	})

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "invalidate", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		self.Invalidate()
		return vm.Nil
	})

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "lockCell:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		self.LockCell(arg0, arg1)
		return vm.Nil
	})

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "put:_:_:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		arg2 := v.ValueToGo(args[2]).(string)
		arg3 := *v.ValueToGo(args[3]).(*pkg.Style)
		r0, r1 := self.Put(arg0, arg1, arg2, arg3)
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "resize:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		self.Resize(arg0, arg1)
		return vm.Nil
	})

	// Skipped: CellBuffer.SetContent (too many parameters: 5)
	cellBufferClass.AddPrimitiveMethod(v.Selectors, "setDirty:_:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		arg2 := v.ValueToGo(args[2]).(bool)
		self.SetDirty(arg0, arg1, arg2)
		return vm.Nil
	})

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "size", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		r0, r1 := self.Size()
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

	cellBufferClass.AddPrimitiveMethod(v.Selectors, "unlockCell:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.CellBuffer)
		arg0 := int(args[0].SmallInt())
		arg1 := int(args[1].SmallInt())
		self.UnlockCell(arg0, arg1)
		return vm.Nil
	})

	eventClipboardClass.AddPrimitiveMethod(v.Selectors, "data", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventClipboard)
		result := self.Data()
		return v.GoToValue(result)
	})

	eventClipboardClass.AddPrimitiveMethod(v.Selectors, "when", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventClipboard)
		result := self.When()
		return v.GoToValue(result)
	})

	eventErrorClass.AddPrimitiveMethod(v.Selectors, "error", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventError)
		result := self.Error()
		return v.GoToValue(result)
	})

	eventErrorClass.AddPrimitiveMethod(v.Selectors, "when", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventError)
		result := self.When()
		return v.GoToValue(result)
	})

	eventInterruptClass.AddPrimitiveMethod(v.Selectors, "data", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventInterrupt)
		result := self.Data()
		return v.GoToValue(result)
	})

	eventInterruptClass.AddPrimitiveMethod(v.Selectors, "when", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventInterrupt)
		result := self.When()
		return v.GoToValue(result)
	})

	eventKeyClass.AddPrimitiveMethod(v.Selectors, "key", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventKey)
		result := self.Key()
		return v.GoToValue(result)
	})

	eventKeyClass.AddPrimitiveMethod(v.Selectors, "modifiers", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventKey)
		result := self.Modifiers()
		return v.GoToValue(result)
	})

	eventKeyClass.AddPrimitiveMethod(v.Selectors, "name", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventKey)
		result := self.Name()
		return v.GoToValue(result)
	})

	eventKeyClass.AddPrimitiveMethod(v.Selectors, "rune", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventKey)
		result := self.Rune()
		return v.GoToValue(result)
	})

	eventKeyClass.AddPrimitiveMethod(v.Selectors, "when", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventKey)
		result := self.When()
		return v.GoToValue(result)
	})

	eventMouseClass.AddPrimitiveMethod(v.Selectors, "buttons", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventMouse)
		result := self.Buttons()
		return v.GoToValue(result)
	})

	eventMouseClass.AddPrimitiveMethod(v.Selectors, "modifiers", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventMouse)
		result := self.Modifiers()
		return v.GoToValue(result)
	})

	eventMouseClass.AddPrimitiveMethod(v.Selectors, "position", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventMouse)
		r0, r1 := self.Position()
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

	eventMouseClass.AddPrimitiveMethod(v.Selectors, "when", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventMouse)
		result := self.When()
		return v.GoToValue(result)
	})

	eventPasteClass.AddPrimitiveMethod(v.Selectors, "end", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventPaste)
		result := self.End()
		return v.GoToValue(result)
	})

	eventPasteClass.AddPrimitiveMethod(v.Selectors, "start", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventPaste)
		result := self.Start()
		return v.GoToValue(result)
	})

	eventPasteClass.AddPrimitiveMethod(v.Selectors, "when", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventPaste)
		result := self.When()
		return v.GoToValue(result)
	})

	eventResizeClass.AddPrimitiveMethod(v.Selectors, "pixelSize", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventResize)
		r0, r1 := self.PixelSize()
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

	eventResizeClass.AddPrimitiveMethod(v.Selectors, "size", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventResize)
		r0, r1 := self.Size()
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

	eventResizeClass.AddPrimitiveMethod(v.Selectors, "when", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventResize)
		result := self.When()
		return v.GoToValue(result)
	})

	eventTimeClass.AddPrimitiveMethod(v.Selectors, "setEventNow", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventTime)
		self.SetEventNow()
		return vm.Nil
	})

	// Skipped: EventTime.SetEventTime (unconvertible parameter type: time.Time)
	eventTimeClass.AddPrimitiveMethod(v.Selectors, "when", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.EventTime)
		result := self.When()
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "attributes:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := pkg.AttrMask(args[0].SmallInt())
		result := self.Attributes(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "background:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := pkg.Color(args[0].SmallInt())
		result := self.Background(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "blink:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.Blink(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "bold:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.Bold(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "decompose", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		r0, r1, r2 := self.Decompose()
		arr := make([]vm.Value, 3)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		arr[2] = v.GoToValue(r2)
		return v.NewArrayWithElements(arr)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "dim:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.Dim(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "foreground:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := pkg.Color(args[0].SmallInt())
		result := self.Foreground(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "getUnderlineColor", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		result := self.GetUnderlineColor()
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "getUnderlineStyle", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		result := self.GetUnderlineStyle()
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "italic:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.Italic(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "normal", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		result := self.Normal()
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "reverse:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.Reverse(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "strikeThrough:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(bool)
		result := self.StrikeThrough(arg0)
		return v.GoToValue(result)
	})

	// Skipped: Style.Underline (unconvertible parameter type: []interface{})
	styleClass.AddPrimitiveMethod(v.Selectors, "url:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(string)
		result := self.Url(arg0)
		return v.GoToValue(result)
	})

	styleClass.AddPrimitiveMethod(v.Selectors, "urlId:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Style)
		arg0 := v.ValueToGo(args[0]).(string)
		result := self.UrlId(arg0)
		return v.GoToValue(result)
	})

	windowSizeClass.AddPrimitiveMethod(v.Selectors, "cellDimensions", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.WindowSize)
		r0, r1 := self.CellDimensions()
		arr := make([]vm.Value, 2)
		arr[0] = v.GoToValue(r0)
		arr[1] = v.GoToValue(r1)
		return v.NewArrayWithElements(arr)
	})

}
