// Code generated by mag wrap encoding/json. DO NOT EDIT.
package wrap_json

import (
	"reflect"
	"fmt"

	pkg "encoding/json"
	"github.com/chazu/maggie/vm"
)

var _ = reflect.TypeOf
var _ = fmt.Errorf

// RegisterPrimitives registers all wrapped Go types and functions with the VM.
func RegisterPrimitives(v *vm.VM) {
	// Type: Decoder
	decoderClass := v.RegisterGoType("Go::Json::Decoder", reflect.TypeOf((*pkg.Decoder)(nil)))
	// Type: Encoder
	encoderClass := v.RegisterGoType("Go::Json::Encoder", reflect.TypeOf((*pkg.Encoder)(nil)))
	// Type: InvalidUTF8Error
	invalidUTF8ErrorClass := v.RegisterGoType("Go::Json::InvalidUTF8Error", reflect.TypeOf((*pkg.InvalidUTF8Error)(nil)))
	// Type: InvalidUnmarshalError
	invalidUnmarshalErrorClass := v.RegisterGoType("Go::Json::InvalidUnmarshalError", reflect.TypeOf((*pkg.InvalidUnmarshalError)(nil)))
	// Type: MarshalerError
	marshalerErrorClass := v.RegisterGoType("Go::Json::MarshalerError", reflect.TypeOf((*pkg.MarshalerError)(nil)))
	// Type: SyntaxError
	syntaxErrorClass := v.RegisterGoType("Go::Json::SyntaxError", reflect.TypeOf((*pkg.SyntaxError)(nil)))
	// Type: UnmarshalFieldError
	unmarshalFieldErrorClass := v.RegisterGoType("Go::Json::UnmarshalFieldError", reflect.TypeOf((*pkg.UnmarshalFieldError)(nil)))
	// Type: UnmarshalTypeError
	unmarshalTypeErrorClass := v.RegisterGoType("Go::Json::UnmarshalTypeError", reflect.TypeOf((*pkg.UnmarshalTypeError)(nil)))
	// Type: UnsupportedTypeError
	unsupportedTypeErrorClass := v.RegisterGoType("Go::Json::UnsupportedTypeError", reflect.TypeOf((*pkg.UnsupportedTypeError)(nil)))
	// Type: UnsupportedValueError
	unsupportedValueErrorClass := v.RegisterGoType("Go::Json::UnsupportedValueError", reflect.TypeOf((*pkg.UnsupportedValueError)(nil)))

	// Package namespace class for class-level methods
	nsClass := v.RegisterGoType("Go::Json", reflect.TypeOf((*struct{})(nil)))
	_ = nsClass

	// Skipped: Compact (unconvertible parameter type: *bytes.Buffer)
	// Skipped: HTMLEscape (unconvertible parameter type: *bytes.Buffer)
	// Skipped: Indent (unconvertible parameter type: *bytes.Buffer)
	nsClass.AddClassMethod(v.Selectors, "marshal:", vm.NewPrimitiveMethod("marshal:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0])
		result, err := pkg.Marshal(arg0)
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	}))

	nsClass.AddClassMethod(v.Selectors, "marshalIndent:_:_:", vm.NewPrimitiveMethod("marshalIndent:_:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := v.ValueToGo(args[0])
		arg1 := v.ValueToGo(args[1]).(string)
		arg2 := v.ValueToGo(args[2]).(string)
		result, err := pkg.MarshalIndent(arg0, arg1, arg2)
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	}))

	// Skipped: NewDecoder (unconvertible parameter type: io.Reader)
	// Skipped: NewEncoder (unconvertible parameter type: io.Writer)
	nsClass.AddClassMethod(v.Selectors, "unmarshal:_:", vm.NewPrimitiveMethod("unmarshal:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := []byte(v.ValueToGo(args[0]).(string))
		arg1 := v.ValueToGo(args[1])
		err := pkg.Unmarshal(arg0, arg1)
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return vm.Nil
	}))

	nsClass.AddClassMethod(v.Selectors, "valid:", vm.NewPrimitiveMethod("valid:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		arg0 := []byte(v.ValueToGo(args[0]).(string))
		result := pkg.Valid(arg0)
		return v.GoToValue(result)
	}))

	decoderClass.AddPrimitiveMethod(v.Selectors, "buffered", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Decoder)
		result := self.Buffered()
		return v.GoToValue(result)
	})

	decoderClass.AddPrimitiveMethod(v.Selectors, "decode:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Decoder)
		arg0 := v.ValueToGo(args[0])
		err := self.Decode(arg0)
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return vm.Nil
	})

	decoderClass.AddPrimitiveMethod(v.Selectors, "disallowUnknownFields", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Decoder)
		self.DisallowUnknownFields()
		return vm.Nil
	})

	decoderClass.AddPrimitiveMethod(v.Selectors, "inputOffset", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Decoder)
		result := self.InputOffset()
		return v.GoToValue(result)
	})

	decoderClass.AddPrimitiveMethod(v.Selectors, "more", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Decoder)
		result := self.More()
		return v.GoToValue(result)
	})

	decoderClass.AddPrimitiveMethod(v.Selectors, "token", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Decoder)
		result, err := self.Token()
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return v.GoToValue(result)
	})

	decoderClass.AddPrimitiveMethod(v.Selectors, "useNumber", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Decoder)
		self.UseNumber()
		return vm.Nil
	})

	encoderClass.AddPrimitiveMethod(v.Selectors, "encode:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Encoder)
		arg0 := v.ValueToGo(args[0])
		err := self.Encode(arg0)
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return vm.Nil
	})

	encoderClass.AddPrimitiveMethod(v.Selectors, "setEscapeHTML:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Encoder)
		arg0 := v.ValueToGo(args[0]).(bool)
		self.SetEscapeHTML(arg0)
		return vm.Nil
	})

	encoderClass.AddPrimitiveMethod(v.Selectors, "setIndent:_:", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.Encoder)
		arg0 := v.ValueToGo(args[0]).(string)
		arg1 := v.ValueToGo(args[1]).(string)
		self.SetIndent(arg0, arg1)
		return vm.Nil
	})

	invalidUTF8ErrorClass.AddPrimitiveMethod(v.Selectors, "error", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.InvalidUTF8Error)
		result := self.Error()
		return v.GoToValue(result)
	})

	invalidUnmarshalErrorClass.AddPrimitiveMethod(v.Selectors, "error", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.InvalidUnmarshalError)
		result := self.Error()
		return v.GoToValue(result)
	})

	marshalerErrorClass.AddPrimitiveMethod(v.Selectors, "error", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.MarshalerError)
		result := self.Error()
		return v.GoToValue(result)
	})

	marshalerErrorClass.AddPrimitiveMethod(v.Selectors, "unwrap", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.MarshalerError)
		err := self.Unwrap()
		if err != nil {
			panic(fmt.Sprintf("Maggie error: GoError: %v", err))
		}
		return vm.Nil
	})

	syntaxErrorClass.AddPrimitiveMethod(v.Selectors, "error", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.SyntaxError)
		result := self.Error()
		return v.GoToValue(result)
	})

	unmarshalFieldErrorClass.AddPrimitiveMethod(v.Selectors, "error", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.UnmarshalFieldError)
		result := self.Error()
		return v.GoToValue(result)
	})

	unmarshalTypeErrorClass.AddPrimitiveMethod(v.Selectors, "error", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.UnmarshalTypeError)
		result := self.Error()
		return v.GoToValue(result)
	})

	unsupportedTypeErrorClass.AddPrimitiveMethod(v.Selectors, "error", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.UnsupportedTypeError)
		result := self.Error()
		return v.GoToValue(result)
	})

	unsupportedValueErrorClass.AddPrimitiveMethod(v.Selectors, "error", func(vmPtr interface{}, receiver vm.Value, args []vm.Value) vm.Value {
		v := vmPtr.(*vm.VM)
		goVal, ok := v.GetGoObject(receiver)
		if !ok {
			return vm.Nil
		}
		self := goVal.(*pkg.UnsupportedValueError)
		result := self.Error()
		return v.GoToValue(result)
	})

}
